# Generated by Django 5.1.4 on 2026-06-22 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error'), ('success', 'Success')], default='idle', max_length=20)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('webhook_secret', models.TextField(blank=True, null=True)),
                ('connection_health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unreachable', 'Unreachable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_config', to='organizations.organization')),
            ],
            options={
                'db_table': 'issuer_integration_config',
            },
        ),
    ]
