# Generated by Django 5.1.4 on 2026-06-26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='webhook_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='integrationconfig',
            old_name='webhook_secret',
            new_name='webhook_secret',
        ),
        # Note: The actual model changes will be detected by Django
        # This migration file is a placeholder - run makemigrations when environment is ready
        migrations.RunSQL(
            sql="""
            -- This migration should be replaced by running: python manage.py makemigrations issuer
            -- The following changes need to be applied:
            -- 1. Add new fields to IntegrationConfig: auth_type, api_key, api_key_header_name, auth_config, 
            --    base_url, api_version, api_protocol, custom_headers, timeout_seconds, rate_limit_per_minute,
            --    retry_backoff_minutes, integration_status, paused_at, revoked_at, revoked_by, revocation_reason,
            --    webhook_enabled, webhook_events, last_error_message, setup_completed_at, setup_step
            -- 2. Create FieldMapping table
            """,
            reverse_sql="",
        ),
    ]
