# Generated by Django 5.1.4 on 2026-06-26 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_integration_config_enhanced_and_field_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='api_key',
            field=models.TextField(blank=True, help_text='API key or token value', null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='api_key_header_name',
            field=models.CharField(blank=True, default='Authorization', help_text='Header name for the API key', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='api_protocol',
            field=models.CharField(choices=[('rest', 'REST API'), ('graphql', 'GraphQL'), ('soap', 'SOAP')], default='rest', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='api_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional auth config (OAuth2 fields, etc.)'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='auth_type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Authentication'), ('oauth2', 'OAuth 2.0'), ('custom_header', 'Custom Header')], default='bearer_token', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='Root URL for the external system API', null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers for API requests'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='integration_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('pending_setup', 'Pending Setup')], default='pending_setup', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='rate_limit_per_minute',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='retry_backoff_minutes',
            field=models.IntegerField(default=5, help_text='Base minutes for exponential backoff'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='revocation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='revoked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='setup_step',
            field=models.IntegerField(default=0, help_text='Current step in the multi-step setup wizard (0 = not started)'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='timeout_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='webhook_events',
            field=models.JSONField(blank=True, default=list, help_text='List of event types to receive via webhook'),
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_field', models.CharField(help_text='Field name/path in the external system', max_length=255)),
                ('external_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON Object'), ('array', 'Array')], default='string', max_length=20)),
                ('external_field_path', models.CharField(blank=True, help_text='JSONPath or dot-notation path for nested fields', max_length=500, null=True)),
                ('external_required', models.BooleanField(default=False)),
                ('platform_field', models.CharField(help_text='Target field name in the platform data model', max_length=255)),
                ('platform_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON Object'), ('array', 'Array')], default='string', max_length=20)),
                ('transform_type', models.CharField(choices=[('direct', 'Direct (1:1)'), ('concat', 'Concatenate'), ('format', 'Format String'), ('lookup', 'Lookup / Enum Map'), ('custom', 'Custom Transform')], default='direct', max_length=20)),
                ('transform_config', models.JSONField(blank=True, default=dict, help_text='Configuration for the transformation (format string, enum map, etc.)')),
                ('default_value', models.TextField(blank=True, help_text='Default value if external field is missing', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Whether mapping is required for sync to proceed')),
                ('order', models.IntegerField(default=0)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='issuer.integrationconfig')),
            ],
            options={
                'db_table': 'issuer_field_mapping',
                'ordering': ['order', 'created_at'],
                'unique_together': {('integration', 'external_field'), ('integration', 'platform_field')},
            },
        ),
    ]
