# Generated by Django 5.1.4 on 2026-06-24 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat_date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_organizations', models.IntegerField(default=0)),
                ('total_credentials', models.IntegerField(default=0)),
                ('active_credentials', models.IntegerField(default=0)),
                ('total_verifications', models.IntegerField(default=0)),
                ('successful_verifications', models.IntegerField(default=0)),
                ('new_credentials_today', models.IntegerField(default=0)),
                ('sync_errors_today', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_portal_stats',
                'ordering': ['-stat_date'],
            },
        ),
    ]
