# Generated by Django 5.1.4 on 2026-06-22 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.CharField(max_length=255)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('credential_type', models.CharField(blank=True, max_length=100)),
                ('result', models.BooleanField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_history',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_credential_id', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField()),
                ('checks', models.JSONField(default=list)),
                ('overall_message', models.CharField(blank=True, max_length=500)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_results', to='credentials.credential')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_result',
            },
        ),
    ]
