# Generated by Django 5.1.4 on 2026-06-22 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_count', models.IntegerField(default=0)),
                ('last_credential_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential_org', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_organization',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('credentials_processed', models.IntegerField(default=0)),
                ('credentials_created', models.IntegerField(default=0)),
                ('credentials_updated', models.IntegerField(default=0)),
                ('credentials_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_sync_log',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('national_id', models.CharField(max_length=255)),
                ('credential_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('pending_match', 'Pending Match')], default='pending_match', max_length=20)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.TextField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_credential',
                'indexes': [models.Index(fields=['holder', 'status'], name='credentials_holder__be93ba_idx'), models.Index(fields=['organization', 'status'], name='credentials_organiz_069e0b_idx'), models.Index(fields=['credential_id'], name='credentials_credent_1a7bdc_idx'), models.Index(fields=['national_id', 'organization'], name='credentials_nationa_4bbef0_idx'), models.Index(fields=['updated_at'], name='credentials_updated_a2c2f7_idx')],
            },
        ),
    ]
