# Generated by Django 5.1.4 on 2026-06-22 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('did', models.CharField(max_length=500, unique=True)),
                ('document', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='did_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'did_document',
            },
        ),
        migrations.CreateModel(
            name='DIDKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_key_hex', models.CharField(max_length=500)),
                ('encrypted_private_key', models.TextField()),
                ('key_type', models.CharField(default='Ed25519', max_length=50)),
                ('purpose', models.CharField(choices=[('authentication', 'Authentication'), ('assertionMethod', 'Assertion Method')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('did_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='did.diddocument')),
            ],
            options={
                'db_table': 'did_key',
            },
        ),
    ]
