# Generated by Django 5.1.4 on 2026-06-24 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_holder_org_mapping'),
        ('organizations', '0003_fix_base_api_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holderorgmapping',
            name='unique_holder_org',
        ),
        migrations.RenameIndex(
            model_name='holderorgmapping',
            new_name='holder_hold_holder__df9f24_idx',
            old_name='holder_org_idx',
        ),
        migrations.RenameIndex(
            model_name='holderorgmapping',
            new_name='holder_hold_organiz_d55dc3_idx',
            old_name='org_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='holderorgmapping',
            unique_together={('holder', 'organization')},
        ),
    ]
